name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: BloodHound set up python on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Native Binary
      run: |
        pip install pyinstaller
        python setup.py build
        python setup.py install
        pyinstaller -F bloodhound.py
    - name: Upload Windows Binary
      if: runner.os == 'windows'
      uses: actions/upload-artifact@v3
      with:
        name: bloodhound.exe
        path: dist/bloodhound.exe
    - name: Upload Nix/OSx Binary
      if: runner.os != 'windows'
      uses: actions/upload-artifact@v3
      with:
        name: bloodhound-${{ matrix.os }}
        path: dist/bloodhound
